MAE-358: Display the Member only event settings link under event configurations menu
compucorp/uk.co.compucorp.membersonlyevent pull request #28
Opened 2022-04-26 07:52 UTC by olayiwola-compucorp

## Overview
This PR adds the Member-only event settings under the event configurations menu.

## Before
<img width="1073" alt="Screenshot 2022-04-26 at 08 50 04" src="https://user-images.githubusercontent.com/85277674/165249672-23a03768-d916-423e-a383-56706573d9ff.png">

## After
<img width="1087" alt="Screenshot 2022-04-26 at 08 44 03" src="https://user-images.githubusercontent.com/85277674/165249633-8713675b-62f9-4c8c-89db-53f43ef8de40.png">

2022-04-26 08:32 UTC, ahed-compucorp submitted a review, later dismissed

2022-04-26 09:24 UTC, erawat commented
@olayiwola-compucorp  Can you confirm when clicking Members Only Event Settings link, the tab will be landed in the Members Only Event Settings tab?

2022-04-27 07:48 UTC, olayiwola-compucorp commented
> @olayiwola-compucorp Can you confirm when clicking Members Only Event Settings link, the tab will be landed in the Members Only Event Settings tab?

Yes @erawat I have updated the PR description with a gif to show this.

2022-05-05 09:52 UTC, erawat commented on CRM/MembersOnlyEvent/Form/MembersOnlyEventTab.php
> +   * Set variables up before form is built.
/s/Set/Sets

2022-05-05 10:03 UTC, erawat requested changes

2022-05-05 10:03 UTC, erawat commented on CRM/MembersOnlyEvent/Form/MembersOnlyEventTab.php
> +   * Set variables up before form is built.
/s/Set/Sets

2022-05-05 10:03 UTC, erawat commented on CRM/MembersOnlyEvent/Hook/Tabset/Event.php
> +      return;
Should have an empty line before return.

2022-05-05 11:42 UTC, erawat approved these changes

2022-05-05 11:51 UTC, merged